name: Build and push manually a nightly Docker-Influxdb-Grafana-Telegraf image

on:
  # cron job to trigger the build on any push to dev
  #push:
  #branches:
  #  - paths: 'Dockerfile_nightly'
  #  - 'main'
  schedule:
  # cron job to trigger the build dialy (time in UTC)
    - cron:  '0 4 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Manually trigger nightly run'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name from date
        id: tag_date
        run: echo "TAG_DATE=$(date +'%Y%m%d')" >>$GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push latest
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64/v8
          push: true
          tags: pluim003/influxdb2-grafana-telegraf:nightly
